config/routes.rb
Project2::Application.routes.draw do

  root to: "episodes#index"

  resources :episodes, only: [:index, :show]
  resources :actors, only: [:index, :show]

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :actorepisodes
  has_many :episodes, :through => :actorepisodes

end

app/models/actorepisode.rb
class Actorepisode < ActiveRecord::Base
  belongs_to :actor
  belongs_to :episode

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  has_many :actorepisodes
  has_many :actors, :through => :actorepisodes

end

app/controllers/actorepisodes_controller.rb
class ActorepisodesController < ApplicationController
  def index
    @actorepisodes = Actorepisodes.all
  end
  
  def index
    @actorepisode = Actorepisodes.find(params[:id])
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
  end

  def show
    @actor = Actor.find(params[:id])
  end


  private
  def actor
    params.require(:actor_id).permit(:name, :character, :first_name, :last_name, :img_url, :imdb_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def index
    @episodes = Episode.all
  end
  def show
    @episode = Episode.find(params[:id])
  end


  private
  def episode_params
    params.require(:episode_id).permit(:title, :air_date, :synopsis )
  end

end

app/helpers/actorepisodes_helper.rb
module ActorepisodesHelper
  def actor_in_episodes(actor)
    where("name_id =", actor)
  end

  def actors_in_episode(episode)
    where("episode_id =", episide)
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/actors/index.html.erb
<div class=centerl>
  <h1>List of Actors</h1>
<% sorted = @actors.sort_by &:last_name  %>
<% sorted.each do |actor| %>
    <p><%= link_to actor.name, actor_path(actor) %> -  <%= actor.character %></p>
<% end %>
</div>

app/views/actors/savetext.html.erb
<% eps = @actor.episodes  %>
<% eps.each do |ep|  %>
<p><%=   ep.title  %></p>
  <%end%>

app/views/actors/show.html.erb
<div class=centerl>
<h1><%= @actor.name %></h1>
<h3><%= @actor.character %></h3>
<%= image_tag(@actor.img_url) %>
</div>


<div class=centerr>
  <h2> Episodes </h2>
  <% if @actor.actorepisodes.any?  %>
  <% @actor.actorepisodes.each do |actorepisode|  %>
    <p><%= link_to actorepisode.episode.title, episode_path(actorepisode.episode) %> </p>
  <%end%>
<%end%>

</div>

app/views/episodes/index.html.erb
<div class=centerl>
<h1>All Episodes </h1>
<% @episodes.each do |episode| %>
      <p><%= link_to episode.title, episode_path(episode)%> - <%= episode.air_date %> </p>
<% end %>
<div>
  <div class=centerr>
  </div>

app/views/episodes/show.html.erb
<div class=centerl>
<h1><%= @episode.title %></h1>
<h3><%= @episode.air_date %></h3>
<article> <%= @episode.synopsis %></article>
</div>

<div class=centerr>
    <h2> Cast </h2>
<% if @episode.actorepisodes.any?  %>
  <% @episode.actorepisodes.each do |actorepisode|  %>
    <p><%= link_to actorepisode.actor.name, actor_path(actorepisode.actor) %> -  <%= actorepisode.actor.character %> </p>
  <%end%>
<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>M*A*S*H Reference Site</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body><div id=heading>
</div>
<div id=buttoncontainer>
  <%= link_to "View Actors", actors_path %> | <%= link_to "View Episodes", episodes_path %>
</div>
<div id=main>
  <div class=left>
  </div>
    <%= yield %>
  <div class=right>
  </div>




</div>

</body>
</html>